- hosts: all
  connection: local
  become: yes
  # roles:
  # - fubarhouse.golang
  # vars:
  #   go_get:
  #     - name: amass
  #       url: github.com/OWASP/Amass
  #     - name: subfinder
  #       url: github.com/subfinder/subfinder
  #     - name: zdns
  #       url: github.com/zmap/zdns
  #     - name: gitleaks
  #       url: github.com/zricethezav/gitleaks
  tasks:
    - name: Add Kali Repo Key
      apt_key:
        url: https://archive.kali.org/archive-key.asc
        state: present
    - name: Add Kali Repo
      apt_repository:
        repo: deb http://http.kali.org/kali kali-rolling main contrib non-free
        state: present


    - name: Create tools directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - '/home/vagrant/tools/'
        - '/home/vagrant/tools/web'
        - '/home/vagrant/tools/web/aquatone'
        - '/home/vagrant/tools/sql'
        - '/home/vagrant/tools/ad'
        - '/home/vagrant/tools/linux'
        - '/home/vagrant/tools/network'
        - '/home/vagrant/tools/windows'
        - '/home/vagrant/tools/shells'
        - '/home/vagrant/tools/exploits'
        - '/home/vagrant/tools/static_analysis'
        - '/home/vagrant/tools/osint/'
        - '/home/vagrant/tools/osint/linkedin'

