- hosts: all
  connection: local
  become: yes
  # roles:
  # - fubarhouse.golang
  # vars:
  #   go_get:
  #     - name: amass
  #       url: github.com/OWASP/Amass
  #     - name: subfinder
  #       url: github.com/subfinder/subfinder
  #     - name: zdns
  #       url: github.com/zmap/zdns
  #     - name: gitleaks
  #       url: github.com/zricethezav/gitleaks
  tasks:
    - name: Install Pentest Tooling (Info Gathering - Network)
      apt:
        name: [nmap,p0f,hping3,wireshark,enum4linux,smbmap,arp-scan,cdpsnarf,masscan,smtp-user-enum,tcpdump]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Info Gathering - DNS)
      apt:
        name: [dnswalk,dnsenum,sublist3r,urlcrazy]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Info Gathering - Other)
      apt:
        name: [recon-ng,eyewitness,nikto]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success




    - name: Install Pentest Tooling (TLS)
      apt:
        name: [sslsplit,sslstrip,sslyze,sslscan]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success




    - name: Install Pentest Tooling (Web - Directory Busting)
      apt:
        name: [dirb,dirbuster,gobuster]
    - name: Install Pentest Tooling (Web - SQL)
      apt: 
        name: [sqlmap,jsql]
        state: present
    - name: Install Pentest Tooling (Web - SQL)
      git:
        repo: https://github.com/mysqludf/lib_mysqludf_sys.git
        version: master
        depth: 1
        dest: /home/vagrant/tools/sql/lib_mysqludf_sys/
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Web - NoSQL)
      git:
        repo: https://github.com/codingo/NoSQLMap.git
        version: master
        dest: /home/vagrant/tools/sql/nosqlmap
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Web)
      apt:
        name: [burpsuite,dotdotpwn,wpscan,wfuzz,apache-users,davtest,joomscan,padbuster,webshells]
        state: present
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Web - Droopescan)
      pip:
        executable: /usr/bin/pip3
        name: droopescan
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Web - Aquatone)
      unarchive:
        src: https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip
        dest: /home/vagrant/tools/web/aquatone/
        remote_src: yes
      register: apt_res
      retries: 5
      until: apt_res is success
    

    - name: Install Pentest Tooling (Linux Enum)
      git:
        repo: https://github.com/rebootuser/LinEnum.git
        version: master
        dest: /home/vagrant/tools/linux/lin_enum/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Linux Kernel Exploits)
      git:
        repo: https://github.com/xairy/kernel-exploits.git
        version: master
        depth: 1
        dest: /home/vagrant/tools/linux/linux_kernel_exploits
      register: apt_res
      retries: 5
      until: apt_res is success


    - name: Install Pentest Tooling (Routersploit)
      git:
        repo: https://github.com/threat9/routersploit.git
        version: master
        dest: /home/vagrant/tools/network/routersploit
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Routersploit Install)
      pip:
        executable: /usr/bin/pip3
        requirements: /home/vagrant/tools/network/routersploit/requirements.txt
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Active Directory)
      apt:
        name: [responder,bloodhound,crackmapexec,powersploit]
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - Impacket)
      git:
        repo: https://github.com/SecureAuthCorp/impacket.git
        version: master
        dest: /home/vagrant/tools/ad/impacket/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - Impacket)
      pip:
        executable: /usr/bin/pip3
        name: impacket
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - MITM6)
      git:
        repo: https://github.com/fox-it/mitm6.git
        version: master
        dest: /home/vagrant/tools/ad/mitm6/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - MITM6)
      pip:
        requirements: /home/vagrant/tools/ad/mitm6/requirements.txt
        executable: /usr/bin/pip3
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - DomainPasswordSpray)
      git:
        repo: https://github.com/dafthack/DomainPasswordSpray.git
        version: master
        dest: /home/vagrant/tools/ad/DomainPasswordSpray/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success


    # - name: Install Pentest Tooling (MSF)
    #   apt:
    #     name:
    - name: Install Pentest Tooling (ExploitDB)
      git:
        repo: https://github.com/offensive-security/exploitdb.git
        version: master
        dest: /home/vagrant/tools/exploits/exploit_db/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (ExploitDB Bin Sploits)
      git:
        repo: https://github.com/offensive-security/exploitdb-bin-sploits.git
        version: master
        dest: /home/vagrant/tools/exploits/bin_sploits/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Exploits)
      git:
        repo: https://github.com/XiphosResearch/exploits.git
        dest: /home/vagrant/tools/exploits/xiphos_research_exploits
        version: master
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success

      
    - name: Install Pentest Tooling (Reporting)
      apt:
        name: [keepnote,cherrytree]



  
    - name: Install Pentest Tooling (Reversing, Android, Hardware)
      apt:
        name: [edb-debugger, javasnoop, jd-gui, ollydbg, valgrind, yara, arduino, binwalk]
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Reversing, Android, Hardware) - Install Frida
      pip: 
        executable: /usr/bin/pip3
        name: frida-tools
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Android Tooling
      apt:
        name: [apktool,dex2jar, smali, android-sdk]
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Android Tooling - Drozer
      apt:
        deb: https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer_2.4.4.deb
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Mobile Tooling
      docker_image:
        name: opensecurity/mobile-security-framework-mobsf
        source: pull
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Static Analysis)
      git:
        name: https://github.com/jeremylong/DependencyCheck.git
        version: master
        dest: /home/vagrant/tools/static_analysis/DependencyCheck/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
