- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install Pentest Tooling (Exploits - ExploitDB)
      git:
        repo: https://github.com/offensive-security/exploitdb.git
        version: master
        dest: /home/vagrant/tools/exploits/exploit_db/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Exploits - ExploitDB Bin Sploits)
      git:
        repo: https://github.com/offensive-security/exploitdb-bin-sploits.git
        version: master
        dest: /home/vagrant/tools/exploits/bin_sploits/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Exploits - XiphosResearch)
      git:
        repo: https://github.com/XiphosResearch/exploits.git
        dest: /home/vagrant/tools/exploits/xiphos_research_exploits
        version: master
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Exploits - Linux Kernel Exploits)
      git:
        repo: https://github.com/xairy/kernel-exploits.git
        version: master
        depth: 1
        dest: /home/vagrant/tools/linux/linux_kernel_exploits
      register: apt_res
      retries: 5
      until: apt_res is success




    - name: Install Pentest Tooling (Linux Enum)
      git:
        repo: https://github.com/rebootuser/LinEnum.git
        version: master
        dest: /home/vagrant/tools/linux/lin_enum/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (One-Lin3r)
      pip:
        name: one-lin3r
        executable: /usr/bin/pip3
      register: apt_res
      retries: 5
      until: apt_res is success