- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install Pentest Tooling (Mobile - MobSF)
      docker_image:
        name: opensecurity/mobile-security-framework-mobsf
        source: pull
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Mobile - Install Frida)
      pip: 
        executable: /usr/bin/pip3
        name: frida-tools
      register: apt_res
      retries: 5
      until: apt_res is success
    
    - name: Install Pentest Tooling (Mobile -  Android)
      apt:
        name: [apktool,dex2jar, smali, android-sdk]
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Mobile - Drozer)
      apt:
        deb: https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer_2.4.4.deb
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Mobile - Android - Qark)
      git:
        repo: https://github.com/linkedin/qark/
        version: master
        dest: /home/vagrant/tools/mobile/qark/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    # - name: Install Pentest Tooling (Mobile - Android - Qark)
    #   pip:
    #     requirements: /home/vagrant/tools/mobile/qark/requirements.txt
    #     executable: /usr/bin/pip3
    #   register: apt_res
    #   retries: 5
    #   until: apt_res is success