- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install Pentest Tooling (Reporting)
      apt:
        name: [keepnote,cherrytree]
      register: apt_res
      retries: 5
      until: apt_res is success