- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install Pentest Tooling (Web)
      apt:
        name: [burpsuite,dotdotpwn,wpscan,wfuzz,apache-users,davtest,joomscan,padbuster,webshells]
        state: present
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Web - Jython for BurpSuite)
      get_url:
        url: https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar
        dest: /home/vagrant/downloads/jython-standalone-2.7.1.jar
        mode: '0440'
      register: apt_res
      retries: 5
      until: apt_res is success



    - name: Install Pentest Tooling (Web - Directory Busting)
      apt:
        name: [dirb,dirbuster,gobuster]
    - name: Install Pentest Tooling (Web - SQL)
      apt: 
        name: [sqlmap,jsql]
        state: present
      register: apt_res
      retries: 5
      until: apt_res is success


    - name: Install Pentest Tooling (Web - SQL)
      git:
        repo: https://github.com/mysqludf/lib_mysqludf_sys.git
        version: master
        depth: 1
        dest: /home/vagrant/tools/sql/lib_mysqludf_sys/
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Web - NoSQL)
      git:
        repo: https://github.com/codingo/NoSQLMap.git
        version: master
        dest: /home/vagrant/tools/sql/nosqlmap
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Web - Droopescan)
      pip:
        executable: /usr/bin/pip3
        name: droopescan
      register: apt_res
      retries: 5
      until: apt_res is success
      
    - name: Install Pentest Tooling (Web - Aquatone)
      unarchive:
        src: https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip
        dest: /home/vagrant/tools/web/aquatone/
        remote_src: yes
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Web - YoSerial)
      get_url:
        url: https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar
        dest: /home/vagrant/tools/web/yoserial.jar
        mode: '0440'
      register: apt_res
      retries: 5
      until: apt_res is success