- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install Pentest Tooling (Active Directory)
      apt:
        name: [responder,bloodhound,crackmapexec,powersploit]
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - Impacket)
      git:
        repo: https://github.com/SecureAuthCorp/impacket.git
        version: master
        dest: /home/vagrant/tools/ad/impacket/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - Impacket)
      pip:
        executable: /usr/bin/pip3
        name: impacket
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - MITM6)
      git:
        repo: https://github.com/fox-it/mitm6.git
        version: master
        dest: /home/vagrant/tools/ad/mitm6/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - MITM6)
      pip:
        requirements: /home/vagrant/tools/ad/mitm6/requirements.txt
        executable: /usr/bin/pip3
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Active Directory - DomainPasswordSpray)
      git:
        repo: https://github.com/dafthack/DomainPasswordSpray.git
        version: master
        dest: /home/vagrant/tools/ad/DomainPasswordSpray/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success



    - name: Install Pentest Tooling (Active Directory - SharHound)
      git:
        repo: https://github.com/BloodHoundAD/SharpHound
        version: master
        dest: /home/vagrant/tools/ad/SharpHound/
        depth: 1
      register: apt_res
      retries: 5

    - name: Install Pentest Tooling (Active Directory - NTDSAudit)
      get_url:
        url: https://github.com/Dionach/NtdsAudit/releases/download/v2.0.7/NtdsAudit.exe
        dest: /home/vagrant/ad/NtdsAudit.exe
        mode: '0440'
      register: apt_res
      retries: 5
      until: apt_res is success