- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Remove Kali Repo Key
      apt_key:
        state: absent
        id: 7D8D0BF6
    - name: Remove Kali Repo
      apt_repository:
        repo: deb http://http.kali.org/kali kali-rolling main contrib non-free
        state: absent