- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install Pentest Tooling (Static Analysis - DependencyCheck)
      git:
        name: https://github.com/jeremylong/DependencyCheck.git
        version: master
        dest: /home/vagrant/tools/static_analysis/DependencyCheck/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success