- hosts: all
  connection: local
  become: yes
  # roles:
  # - fubarhouse.golang
  # vars:
  #   go_get:
  #     - name: amass
  #       url: github.com/OWASP/Amass
  #     - name: subfinder
  #       url: github.com/subfinder/subfinder
  #     - name: zdns
  #       url: github.com/zmap/zdns
  #     - name: gitleaks
  #       url: github.com/zricethezav/gitleaks
  tasks:
    - name: Install Pentest Tooling (Info Gathering - Network)
      apt:
        name: [nmap,p0f,hping3,wireshark,enum4linux,smbmap,arp-scan,cdpsnarf,masscan,smtp-user-enum,tcpdump]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Info Gathering - DNS)
      apt:
        name: [dnswalk,dnsenum,sublist3r,urlcrazy]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Info Gathering - Other)
      apt:
        name: [recon-ng,eyewitness,nikto,metasploit-framework]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success




    - name: Install Pentest Tooling (TLS)
      apt:
        name: [sslsplit,sslstrip,sslyze,sslscan]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Pentest Tooling (Routersploit)
      git:
        repo: https://github.com/threat9/routersploit.git
        version: master
        dest: /home/vagrant/tools/network/routersploit
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Pentest Tooling (Routersploit Install)
      pip:
        executable: /usr/bin/pip3
        requirements: /home/vagrant/tools/network/routersploit/requirements.txt
      register: apt_res
      retries: 5
      until: apt_res is success
