- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Create resources directory
      file:
        path: "/home/vagrant/resources/"
        state: directory
    - name: Resources - Awesome Pentest
      git:
        repo: https://github.com/enaqx/awesome-pentest.git
        version: master
        dest: /home/vagrant/resources/awesome-pentest/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Awesome Appsec
      git:
        repo: https://github.com/paragonie/awesome-appsec.git
        version: master
        dest: /home/vagrant/resources/awesome-appsec/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Awesome OSINT
      git:
        repo: https://github.com/jivoi/awesome-osint.git
        version: master
        dest: /home/vagrant/resources/awesome-osint/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Awesome Web Security
      git:
        repo: https://github.com/qazbnm456/awesome-web-security.git
        version: master
        dest: /home/vagrant/resources/awesome-web-security/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Awesome Hacking
      git:
        repo: https://github.com/Hack-with-Github/Awesome-Hacking.git
        version: master
        dest: /home/vagrant/resources/awesome-hacking/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Reverse Engineering
      git:
        repo: https://github.com/wtsxDev/reverse-engineering.git
        version: master
        dest: /home/vagrant/resources/reverse-engineering-resources/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Awesome CTF
      git:
        repo: https://github.com/apsdehal/awesome-ctf.git
        version: master
        dest: /home/vagrant/resources/awesome-ctf
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Awesome Security
      git:
        repo: https://github.com/sbilly/awesome-security
        version: master
        dest: /home/vagrant/resources/awesome-security/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - API Security Checklist
      git:
        repo: https://github.com/shieldfy/API-Security-Checklist.git
        version: master
        dest: /home/vagrant/resources/api-security-checklist/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Linux Insides
      git:
        repo: https://github.com/0xAX/linux-insides.git
        version: master
        dest: /home/vagrant/resources/linux-insides/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - Security Guide For Developers
      git: 
        repo: https://github.com/FallibleInc/security-guide-for-developers.git
        version: master
        dest: /home/vagrant/resources/developer_security_guide/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - ExploitDB Papers
      git:
        repo: https://github.com/offensive-security/exploitdb-papers.git
        version: master
        dest: /home/vagrant/resources/exploit_db_papers/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Resources - OWASP Cheatsheets
      git:
        repo: https://github.com/OWASP/CheatSheetSeries.git
        version: master
        dest: /home/vagrant/resources/exploit_db_papers/
        depth: 1
      register: apt_res
      retries: 5
      until: apt_res is success