- hosts: all
  connection: local
  sudo: yes
  # roles:
  # - fubarhouse.golang
  # vars:
  #   go_get:
  #     - name: amass
  #       url: github.com/OWASP/Amass
  #     - name: subfinder
  #       url: github.com/subfinder/subfinder
  #     - name: zdns
  #       url: github.com/zmap/zdns
  #     - name: gitleaks
  #       url: github.com/zricethezav/gitleaks
  tasks:
    - name: Add Kali Repo Key
      apt_key:
        url: https://archive.kali.org/archive-key.asc
        state: present
    - name: Add Kali Repo
      apt_repository:
        repo: deb http://http.kali.org/kali kali-rolling main contrib non-free
        state: present


    - name: Create tools directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - '/home/vagrant/tools/'
        - '/home/vagrant/tools/web'
        - '/home/vagrant/tools/web/aquatone'
        - '/home/vagrant/tools/sql'
        - '/home/vagrant/tools/ad'
        - '/home/vagrant/tools/linux'
        - '/home/vagrant/tools/network'
        - '/home/vagrant/tools/windows'
        - '/home/vagrant/tools/shells'
        - '/home/vagrant/tools/exploits'
        - '/home/vagrant/tools/static_analysis'
        - '/home/vagrant/tools/osint/'
        - '/home/vagrant/tools/osint/linkedin'



    - name: Install Pentest Tooling (Info Gathering - Network)
      apt:
        name: [nmap,p0f,hping3,wireshark,enum4linux,snmpcheck,smbmap,arp-scan,cdpsnarf,masscan,smtp-user-enum,tcpdump]
        state: present
    - name: Install Pentest Tooling (Info Gathering - DNS)
      apt:
        name: [dnsmap,dnswalk,dnsenum,sublist3r,urlcrazy]
        state: present
    - name: Install Pentest Tooling (Info Gathering - Other)
      apt:
        name: [recon-ng,automater,eyewitness,nikto]
        state: present



    - name: Install Pentest Tooling (TLS)
      apt:
        name: [sslsplit,sslstrip,sslyze,sslscan]
        state: present




    - name: Install Pentest Tooling (Web - Directory Busting)
      apt:
        name: [dirb,dirbuster,gobuster]
    - name: Install Pentest Tooling (Web - SQL)
      apt: 
        name: [sqlmap,jsql]
        state: present
    - name: Install Pentest Tooling (Web - SQL)
      git:
        repo: https://github.com/mysqludf/lib_mysqludf_sys.git
        version: master
        depth: 1
        dest: /home/vagrant/tools/sql/lib_mysqludf_sys/
    - name: Install Pentest Tooling (Web - NoSQL)
      git:
        repo: https://github.com/codingo/NoSQLMap.git
        version: master
        dest: /home/vagrant/tools/sql/nosqlmap
        depth: 1
    - name: Install Pentest Tooling (Web)
      apt:
        name: [burpsuite,dotdotpwn,wpscan,wfuzz,apache-users,arachni,davtest,joomscan,padbuster,webshells]
        state: present
    - name: Install Pentest Tooling (Web - Droopescan)
      pip:
        executable: /usr/bin/pip3
        name: droopescan
    - name: Install Pentest Tooling (Web - Aquatone)
      unarchive:
        src: https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip
        dest: /home/vagrant/tools/web/aquatone/
        remote_src: yes

    

    - name: Install Pentest Tooling (Linux Enum)
      git:
        repo: https://github.com/rebootuser/LinEnum.git
        version: master
        dest: /home/vagrant/tools/linux/lin_enum/
        depth: 1
    - name: Install Pentest Tooling (Linux Kernel Exploits)
      git:
        repo: https://github.com/xairy/kernel-exploits.git
        version: master
        depth: 1
        dest: /home/vagrant/tools/linux/linux_kernel_exploits



    - name: Install Pentest Tooling (Routersploit)
      git:
        repo: https://github.com/threat9/routersploit.git
        version: master
        dest: /home/vagrant/tools/network/routersploit
    - name: Install Pentest Tooling (Routersploit Install)
      pip:
        executable: /usr/bin/pip3
        requirements: /home/vagrant/tools/network/routersploit/requirements.txt


    - name: Install Pentest Tooling (Active Directory)
      apt:
        name: [responder,bloodhound,crackmapexec,powersploit]
    - name: Install Pentest Tooling (Active Directory - Impacket)
      git:
        repo: https://github.com/SecureAuthCorp/impacket.git
        version: master
        dest: /home/vagrant/tools/ad/impacket/
        depth: 1
    - name: Install Pentest Tooling (Active Directory - Impacket)
      pip:
        executable: /usr/bin/pip3
        name: impacket
    - name: Install Pentest Tooling (Active Directory - MITM6)
      git:
        repo: https://github.com/fox-it/mitm6.git
        version: master
        dest: /home/vagrant/tools/ad/mitm6/
        depth: 1
    - name: Install Pentest Tooling (Active Directory - MITM6)
      pip:
        requirements: /home/vagrant/tools/ad/mitm6/requirements.txt
        executable: /usr/bin/pip3
    - name: Install Pentest Tooling (Active Directory - DomainPasswordSpray)
      git:
        repo: https://github.com/dafthack/DomainPasswordSpray.git
        version: master
        dest: /home/vagrant/tools/ad/DomainPasswordSpray/
        depth: 1


    # - name: Install Pentest Tooling (MSF)
    #   apt:
    #     name:
    - name: Install Pentest Tooling (ExploitDB)
      git:
        repo: https://github.com/offensive-security/exploitdb.git
        version: master
        dest: /home/vagrant/tools/exploits/exploit_db/
        depth: 1
    - name: Install Pentest Tooling (ExploitDB Bin Sploits)
      git:
        repo: https://github.com/offensive-security/exploitdb-bin-sploits.git
        version: master
        dest: /home/vagrant/tools/exploits/bin_sploits/
        depth: 1
    - name: Install Pentest Tooling (Exploits)
      git:
        repo: https://github.com/XiphosResearch/exploits.git
        dest: /home/vagrant/tools/exploits/xiphos_research_exploits
        version: master
        depth: 1


      
    - name: Install Pentest Tooling (Reporting)
      apt:
        name: [keepnote,cherrytree]



  
    - name: Install Pentest Tooling (Reversing, Android, Hardware)
      apt:
        name: [apktool, dex2jar, edb-debugger, jad, javasnoop, jd-gui, ollydbg, smali, valgrind, yara, android-sdk, arduino, sakis3g,binwalk]
    - name: Install Pentest Tooling (Reversing, Android, Hardware) - Install Frida
      pip: 
        executable: /usr/bin/pip3
        name: frida-tools

    - name: Install Pentest Tooling (Static Analysis)
      git:
        name: https://github.com/jeremylong/DependencyCheck.git
        version: master
        dest: /home/vagrant/tools/static_analysis/DependencyCheck/
        depth: 1