- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Dev Tools Install
      snap:
        name: code-insiders
        classic: yes
      register: apt_res
      retries: 5
      until: apt_res is success