- hosts: all
  connection: local
  sudo: yes
  tasks:
    - name: Add Crystal Key
      shell: curl -sL https://keybase.io/crystal/pgp_keys.asc | sudo apt-key add -

    - name: Add Crystal Apt repository
      apt_repository:
        repo: "deb https://dist.crystal-lang.org/apt crystal main"
        state: present

    - name: Install Crystal
      apt: 
        name: crystal
        update_cache: true
        
    - name: Install Java
      apt:
        name: [default-jre]
        update_cache: true