- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Add Crystal Key
      shell: curl -sL https://keybase.io/crystal/pgp_keys.asc | apt-key add -

    - name: Add Crystal Apt repository
      apt_repository:
        repo: "deb https://dist.crystal-lang.org/apt crystal main"
        state: present
        update_cache: yes
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: Install Crystal
      apt: 
        name: crystal
        update_cache: true
      register: apt_res
      retries: 5
      until: apt_res is success
        
    - name: Install libs for extra Crystal StdLib functionality
      apt:
        name: ["libssl-dev","libxml2-dev","libyaml-dev","libgmp-dev","libreadline-dev","libz-dev"]
      register: apt_res
      retries: 5
      until: apt_res is success

    - name: Install Java
      apt:
        name: [default-jre]
        update_cache: true
      register: apt_res
      retries: 5
      until: apt_res is success