- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install Budgie
      apt:
        name: [ubuntu-budgie-desktop, budgie-desktop, budgie-core]
        state: present
        install_recommends: yes
      register: apt_res
      retries: 5
      until: apt_res is success
    - name: setup GUI
      command: "sudo sed -i 's/allowed_users=.*$/allowed_users=anybody/' /etc/X11/Xwrapper.config"
