- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH
    - name: Logging
      ufw:
        name: Set logging
        logging: 'on'