- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Create downloads directory
      file:
        path: "/home/vagrant/downloads/"
        state: directory
    - name: Set keyboard region
      copy: 
        src: ../../files/keyboard
        dest: /etc/default/keyboard
        owner: root
        group: root
        mode: '0644'
    - name: Set hostname
      hostname:
        name: securitybox