- hosts: all
  connection: local
  sudo: yes
  tasks:
    - apt_key:
        url: https://archive.kali.org/archive-key.asc
        state: present
    - apt_repository:
        repo: deb http://http.kali.org/kali kali-rolling main contrib non-free
        state: present
    - apt:
        upgrade: yes
        update_cache: yes
    - copy: src install_pentest_tools.sh
            dest /home/{{username}}/install_pentest_tools.sh
    - shell: /home/{{username}}/install_pentest_tools.sh